import { DocumentStatuses } from "@/page-sections/admin/users/documentsPage";

export const USER_LIST: any[]  = [
  {
    id: "fkki_JgjwEOMmyizDsy6J",
    role: "Editor",
    agency: "Top Reality",
    name: "Zachary Gomez",
    //username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    avatar: "/static/avatar/001-man.svg",
    //position: "Editor",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
    documentStatus: DocumentStatuses.approved,
  },
  {
    id: "CEqmLNf9WjMv0C75NcFgf",
    role: "Subscriber",
    agency: "Meta",
    name: "Amanda Montgomery",
    email: "montgomery@ya.com",
    //username: "amanda-montgomery",
    avatar: "/static/avatar/002-girl.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Enterprise",
    status: "Active",
    documentStatus: DocumentStatuses.approved,

  },
  {
    id: "WiiFzcbNyV507aeUu2rBp",
    agency: "Top Reality",
    role: "Administrator",
    name: "Lester Holland",
    //username: "lester-holland",
    email: "lester75@gmail.com",
    avatar: "/static/avatar/003-boy.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Professional",
    status: "Active",
    documentStatus: DocumentStatuses.approved,

  },
  {
    id: "kblkUheZKBwyYXhpyXZRU",
    role: "Subscriber",
    name: "Max Allison",
    agency: "Linkedin",
    //username: "max-allison",
    email: "max-allison@pochta.io",
    avatar: "/static/avatar/004-woman.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
    documentStatus: DocumentStatuses.approved,

  },
  {
    id: "hJdMmi-XW-bOZXOiIuW06",
    agency: "Best Homes",
    role: "Administrator",
    //username: "r.gregory",
    name: "Richard Gregory",
    email: "gregory@gmail.com",
    avatar: "/static/avatar/005-man-1.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
    documentStatus: DocumentStatuses.waiting,

  },
  {
    id: "66CoRSh1eQDkN0oAygxSD",
    role: "Contributor",
    agency: "Disney",
    name: "Clifford Caldwell",
    //username: "clifford-caldwell",
    email: "clifford-c@gmail.com",
    avatar: "/static/avatar/006-woman-1.svg",
    //position: "Author",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "9PaoctbP_SnUUdyh8JBiI",
    agency: "Best Homes",
    role: "Subscriber",
    name: "Lester Holland",
    //username: "zlester-holland",
    email: "lester75@gmail.com",
    avatar: "/static/avatar/007-boy-1.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "5tctW0dht060GOc7QnUCC",
    role: "Contributor",
    //username: "r.gregory",
    name: "Richard Gregory",
    agency: "Microsoft",
    email: "gregory@gmail.com",
    avatar: "/static/avatar/008-clown.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "854JQyYIWVF03gPbc_L7c",
    role: "Contributor",
    agency: "Wix",
    name: "Max Allison",
    //username: "max-allison",
    email: "max-allison@pochta.io",
    avatar: "/static/avatar/009-firefighter.svg",
    //position: "Subscriber",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "q6cBWeVZIGd2LUkcBMcQ6",
    role: "Editor",
    agency: "Seek",
    name: "Zachary Gomez",
    //username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    avatar: "/static/avatar/010-girl-1.svg",
    //position: "Editor",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "ppgxPwRuh3SrlaPW22GZd",
    role: "Editor",
    agency: "Ui Lib",
    name: "Zachary Gomez",
    //username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    avatar: "/static/avatar/011-man-2.svg",
    //position: "Editor",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "7ZmGReIxe_LDrVBPSFCC6",
    role: "Editor",
    agency: "Ui Lib",
    name: "Zachary Gomez",
    //username: "zachary-gomez",
    email: "zachary-gomez@gmail.com",
    avatar: "/static/avatar/012-woman-2.svg",
    //position: "Editor",
    phone: "(01) 4563 4556",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "_aCdZoo2xSODzQhCg5LTw",
    role: "Editor",
    agency: "Crona",
    name: "Leanne Graham",
    //username: "zachary-gomez",
    avatar: "/static/avatar/013-woman-3.svg",
    email: "sincere@april.biz",
    //position: "Editor",
    phone: "(01) 8031 8031",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "CGTU-mk0xgow_o9W6kBtC",
    avatar: "/static/avatar/014-man-3.svg",
    name: "Ervin Howell",
    agency: "Deckow-Crist",
    email: "hanna@melissa.tv",
    //position: "Editor",
    phone: "(01) 6593 6593",
    role: "Contributor",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "VACOOmoeWyx2mF6vCXIuB",
    avatar: "/static/avatar/017-girl-2.svg",
    name: "Clementine Bauch",
    agency: "Jacobson",
    email: "athan@yesenia.net",
    //position: "Editor",
    phone: "(01) 4447 4447",
    role: "Contributor",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "AJ_S8rp1CS7hSMSk96i-S",
    avatar: "/static/avatar/013-woman-3.svg",
    name: "Leanne Graham",
    agency: "Crona",
    email: "sincere@april.biz",
    //position: "Editor",
    phone: "(01) 8031 8031",
    role: "Administrator",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "mr8IxGgIIgUVZtINltsjT",
    avatar: "/static/avatar/014-man-3.svg",
    name: "Ervin Howell",
    agency: "Deckow-Crist",
    email: "hanna@melissa.tv",
    //position: "Editor",
    phone: "(01) 6593 6593",
    role: "Contributor",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "akaBZL5m5Ljwz6aRfRZ56",
    avatar: "/static/avatar/017-girl-2.svg",
    name: "Clementine Bauch",
    agency: "Jacobson",
    email: "athan@yesenia.net",
    //position: "Editor",
    phone: "(01) 4447 4447",
    role: "Contributor",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "QgE6QsgmmTCyR3kMeprjy",
    avatar: "/static/avatar/013-woman-3.svg",
    name: "Leanne Graham",
    agency: "Crona",
    email: "sincere@april.biz",
    //position: "Editor",
    phone: "(01) 8031 8031",
    role: "Subscriber",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "DosSKpjRxOPpXqT73isjY",
    avatar: "/static/avatar/020-man-4.svg",
    name: "Chelsey Dietrich",
    agency: "Keebler LLC",
    email: "lucio_Hettinger@annie.ca",
    //position: "Editor",
    phone: "(01) 1289 1289",
    role: "Subscriber",
    subscriptionType: "Basic",
    status: "Active",
  },
  {
    id: "RzL-T4dq2LY8kUbNeyr42",
    avatar: "/static/avatar/018-boy-3.svg",
    name: "Patricia Lebsack",
    agency: "Robel-Corkery",
    email: "julianne.OConner@kory.org",
    //position: "Editor",
    phone: "(01) 9623 9623",
    role: "Subscriber",
    subscriptionType: "Basic",
    status: "Active",
  },
];
